/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

import Foundation

import Thrift


public typealias int = Int32

public final class user {


  public init() { }
}

public protocol MultiplicationService {

  ///
  /// - Parameters:
  ///   - a: 
  ///   - b: 
  /// - Returns: int
  /// - Throws: 
  func multiply(a: int, b: int) throws -> int

}

open class MultiplicationServiceClient : TClient /* , MultiplicationService */ {

}

open class MultiplicationServiceProcessor /* MultiplicationService */ {

  typealias ProcessorHandlerDictionary = [String: (Int32, TProtocol, TProtocol, MultiplicationService) throws -> Void]

  public var service: MultiplicationService

  public required init(service: MultiplicationService) {
    self.service = service
  }

}


